#!/bin/sh
echo "Content-Type: application/json"
echo ""
#驱动不同有区别
#uci set wireless.@wifi-iface[0].ApCliEnable=0
uci set wireless.@wifi-iface[1].disabled=1
uci commit
#nr
/etc/init.d/network restart 1>&- 2>&-
sleep 5
ip=`ifconfig apcli0 | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}'`
if [ $ip ]; then
    echo "{\"result\":\"error\"}"
else
    echo "{\"result\":\"sucess\"}"
fi
